# Generated by Django 5.2.4 on 2025-07-10 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registado', models.DateTimeField(auto_now_add=True, verbose_name='Registado em:')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em: ')),
                ('nome_departamento', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registado', models.DateTimeField(auto_now_add=True, verbose_name='Registado em:')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em: ')),
                ('estatus_fornecedor', models.CharField(choices=[('Ativo', 'Ativo'), ('Em Negociação', 'Em Negociação'), ('Desativado', 'Desativado')], default='em_uso', max_length=15, verbose_name='Estatus')),
                ('nome_fornecedor', models.CharField(max_length=100, unique=True, verbose_name='Nome do Fornecedor')),
                ('nif', models.CharField(max_length=11, unique=True, verbose_name='NIF do Fornecedor')),
                ('telefone_contato', models.CharField(max_length=11, verbose_name='Telefone de Contato')),
                ('email_fornecedor', models.EmailField(max_length=254, verbose_name='E-mail do Fornecedor')),
                ('responsavel', models.CharField(max_length=30, verbose_name='Nome do Responsável')),
                ('contrato', models.BooleanField(default=False, verbose_name='Tem contrato?')),
                ('n_contrtato', models.CharField(blank=True, max_length=30, verbose_name='Nº Contrato')),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='LocalTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registado', models.DateTimeField(auto_now_add=True, verbose_name='Registado em:')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em: ')),
                ('marca_equipamento', models.CharField(max_length=100, unique=True, verbose_name='Marca do Equipamento')),
            ],
            options={
                'verbose_name_plural': 'Marca',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registado', models.DateTimeField(auto_now_add=True, verbose_name='Registado em:')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em: ')),
                ('modelo_equipamento', models.CharField(max_length=100, unique=True, verbose_name='Modelo do Equipamento')),
            ],
            options={
                'verbose_name_plural': 'Modelo',
            },
        ),
        migrations.CreateModel(
            name='Nome_Equipamento_1',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registado', models.DateTimeField(auto_now_add=True, verbose_name='Registado em:')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em: ')),
                ('nome_equipamento', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Nome do Equipamento',
                'verbose_name_plural': 'Nomes dos Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='NomeExame',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registado', models.DateTimeField(auto_now_add=True, verbose_name='Registado em:')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em: ')),
                ('nome_exame', models.CharField(max_length=100, unique=True, verbose_name='Nome do Exame')),
            ],
            options={
                'verbose_name_plural': 'Nomes dos Exames',
            },
        ),
        migrations.CreateModel(
            name='PlanosTelemoveis',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registado', models.DateTimeField(auto_now_add=True, verbose_name='Registado em:')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em: ')),
                ('plano', models.CharField(max_length=20, verbose_name='Plano')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor do plano')),
            ],
            options={
                'verbose_name_plural': 'Planos Telemóveis',
            },
        ),
        migrations.CreateModel(
            name='Licencas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registado', models.DateTimeField(auto_now_add=True, verbose_name='Registado em:')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em: ')),
                ('tipo_licenca', models.CharField(max_length=100, unique=True, verbose_name='Nome da Licença')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor da Licença')),
                ('fornecedor_licenca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.fornecedor', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name_plural': 'Licenças',
            },
        ),
        migrations.CreateModel(
            name='emailstrue',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registado', models.DateTimeField(auto_now_add=True, verbose_name='Registado em:')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em: ')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('palavra_passe', models.CharField(max_length=20, verbose_name='Palavra-Passe Inicial do Email')),
                ('tipo_licenca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.licencas', verbose_name='Tipo de Licença')),
            ],
            options={
                'verbose_name_plural': 'Emails TrueClinic',
            },
        ),
        migrations.CreateModel(
            name='Utilizador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registado', models.DateTimeField(auto_now_add=True, verbose_name='Registado em:')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em: ')),
                ('estatus_utilizador', models.CharField(choices=[('Ativo', 'Ativo'), ('Desligado', 'Desligado')], default='em_uso', max_length=10, verbose_name='Estatus')),
                ('nome_utilizador', models.CharField(max_length=100, verbose_name='Nome Utilizador')),
                ('local_trabalho', models.CharField(max_length=15, verbose_name='Local de Trabalho')),
                ('utilizador_plataforma', models.CharField(max_length=15, verbose_name='Utilizador Plataforma')),
                ('departamento_utilizador', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='comum.departamento', verbose_name='Nome Departamento')),
            ],
            options={
                'verbose_name_plural': 'Utilizadores TrueClinic',
            },
        ),
    ]
