# Generated by Django 5.2.4 on 2025-07-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailstrue',
            name='estatus_email',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Desativado', 'Desativado')], default='em_uso', max_length=15, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='utilizador',
            name='estatus_utilizador',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Desativado', 'Desativado')], default='em_uso', max_length=10, verbose_name='Estatus'),
        ),
    ]
