# Generated by Django 5.2.4 on 2025-07-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0002_emailstrue_estatus_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nome_SO',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registado', models.DateTimeField(auto_now_add=True, verbose_name='Registado em:')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em: ')),
                ('nome_sistema_operacional', models.CharField(max_length=20, unique=True, verbose_name='Nome do Sistema Operacional')),
            ],
            options={
                'verbose_name': 'Nome do Sistema Operacional',
                'verbose_name_plural': 'Nomes dos Sistemas Operacionais',
            },
        ),
        migrations.AlterField(
            model_name='nome_equipamento_1',
            name='nome_equipamento',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nome do Esquipamento'),
        ),
    ]
