# Generated by Django 5.2.4 on 2025-07-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0003_nome_so_alter_nome_equipamento_1_nome_equipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailstrue',
            name='email_pessoal',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail Pessoal'),
        ),
    ]
