# Generated by Django 5.2.4 on 2025-07-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0004_emailstrue_email_pessoal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailstrue',
            name='editado',
            field=models.DateTimeField(auto_now=True, verbose_name='Alterado em: '),
        ),
    ]
