# Generated by Django 5.2.4 on 2025-07-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0005_alter_emailstrue_editado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailstrue',
            name='email_pessoal',
        ),
        migrations.AddField(
            model_name='emailstrue',
            name='caixa_compartilhada',
            field=models.BooleanField(default=False, verbose_name='Caixa Compartilhada?'),
        ),
    ]
