# Generated by Django 5.2.4 on 2025-07-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0006_remove_emailstrue_email_pessoal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailstrue',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
    ]
