# Generated by Django 5.2.4 on 2025-07-10 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoTelemovel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registado', models.DateTimeField(auto_now_add=True, verbose_name='Registado em:')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em: ')),
                ('numero_cartao', models.CharField(max_length=15, verbose_name='Número do Cartão')),
                ('pin', models.CharField(max_length=4, verbose_name='PIN do Cartão')),
                ('puk', models.CharField(max_length=10, verbose_name='PUK do Cartão')),
                ('atribuido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.utilizador', verbose_name='Atribuido')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.planostelemoveis', verbose_name='Plano Associado')),
            ],
            options={
                'verbose_name_plural': 'Cartões Telemóveis',
            },
        ),
        migrations.CreateModel(
            name='CraicaoUtilizador',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registado', models.DateTimeField(auto_now_add=True, verbose_name='Registado em:')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em: ')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('setor', models.CharField(choices=[('Gestão', 'Gestão'), ('Financeiro', 'Financeiro'), ('Profissional', 'Profissional'), ('Diretoria', 'Diretoria'), ('Informática', 'Informática'), ('Clínica', 'Clínica'), ('Administração', 'Administração')], max_length=20, verbose_name='Departamento')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail Sugerido')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.utilizador', verbose_name='Nome Solicitante')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registado', models.DateTimeField(auto_now_add=True, verbose_name='Registado em:')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em: ')),
                ('tag_da_porta', models.BooleanField(default=False, verbose_name='Tag da porta')),
                ('numero_tag', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da TAG')),
                ('email_pessoal', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='comum.emailstrue', verbose_name='E-mail Pessoal')),
                ('nome_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.utilizador', verbose_name='Nome do Utilizador')),
            ],
            options={
                'verbose_name_plural': 'Inventário',
            },
        ),
        migrations.CreateModel(
            name='EmailCompartilhado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registado', models.DateTimeField(auto_now_add=True, verbose_name='Registado em:')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em: ')),
                ('email_compartilhado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.emailstrue', verbose_name='Email')),
                ('email_pessoal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='informatica.inventario')),
            ],
            options={
                'verbose_name_plural': 'Emails Compartilhados',
            },
        ),
        migrations.CreateModel(
            name='AparelhoTelemovel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registado', models.DateTimeField(auto_now_add=True, verbose_name='Registado em:')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em: ')),
                ('telemovel', models.BooleanField(blank=True, verbose_name='Telemóvel')),
                ('numero_telefone', models.CharField(blank=True, max_length=20, verbose_name='Numero do Telemóvel')),
                ('marca_esquipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.marca', verbose_name='Marca do Esquipamento')),
                ('modelo_esquipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.modelo', verbose_name='Modelo do Equipamento')),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='informatica.cartaotelemovel')),
                ('nome_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='informatica.inventario')),
            ],
            options={
                'verbose_name_plural': 'Aparelhos',
            },
        ),
        migrations.CreateModel(
            name='InventarioEquipamento',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registado', models.DateTimeField(auto_now_add=True, verbose_name='Registado em:')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em: ')),
                ('estatus_equipamento', models.CharField(choices=[('em_uso', 'Em Uso'), ('desuso', 'Desuso'), ('descartado', 'Descartado')], default='em_uso', max_length=10, verbose_name='Estatus')),
                ('descricao_equipamento', models.TextField(blank=True, verbose_name='Descrição do Equipamento')),
                ('nome_rede', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Nome na Rede')),
                ('numero_serie', models.CharField(max_length=50, unique=True, verbose_name='Número de Série')),
                ('sistema_operacional', models.CharField(blank=True, max_length=100, verbose_name='Sistema Operacional')),
                ('memoria', models.CharField(blank=True, max_length=20, verbose_name='Memoria')),
                ('tamanho', models.CharField(blank=True, max_length=20, verbose_name='Tamanho')),
                ('numero_ip', models.CharField(blank=True, max_length=50, verbose_name='Número do IP')),
                ('mac', models.CharField(blank=True, max_length=20, verbose_name='Mac Address')),
                ('data_compra', models.DateField(verbose_name='Data da Compra')),
                ('data_garantia', models.DateField(verbose_name='Final da Garantia')),
                ('tipo_garantia', models.CharField(blank=True, choices=[('Balcão', 'Balcão'), ('On Site', 'On Site')], max_length=10, verbose_name='Tipo de Garantia')),
                ('fatura', models.FileField(blank=True, upload_to='%Y/%m/%d/', verbose_name='Fatura de Compra')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações Gerais')),
                ('atribuido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.utilizador', verbose_name='Atribuido')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.fornecedor', verbose_name='Fornecedor')),
                ('marca_esquipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.marca', verbose_name='Marca do Esquipamento')),
                ('modelo_esquipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.modelo', verbose_name='Modelo do Equipamento')),
                ('nome_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.nome_equipamento_1', verbose_name='Nome do Equipamento')),
            ],
            options={
                'verbose_name_plural': 'Equipamentos TrueClinic',
            },
        ),
        migrations.CreateModel(
            name='Equipamentos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registado', models.DateTimeField(auto_now_add=True, verbose_name='Registado em:')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em: ')),
                ('nome_utilizador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='informatica.inventario')),
                ('nome_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='informatica.inventarioequipamento', verbose_name='Equipamento')),
            ],
            options={
                'verbose_name_plural': 'Equipamentos',
            },
        ),
    ]
