# Generated by Django 5.2.4 on 2025-07-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartaotelemovel',
            name='numero_telefone',
            field=models.CharField(default=4, max_length=15, verbose_name='Número do Telefone'),
            preserve_default=False,
        ),
    ]
