# Generated by Django 5.2.4 on 2025-07-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0002_cartaotelemovel_numero_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartaotelemovel',
            name='numero_cartao',
            field=models.CharField(blank=True, max_length=15, verbose_name='Número do Cartão'),
        ),
        migrations.AlterField(
            model_name='cartaotelemovel',
            name='pin',
            field=models.CharField(blank=True, max_length=4, verbose_name='PIN do Cartão'),
        ),
        migrations.AlterField(
            model_name='cartaotelemovel',
            name='puk',
            field=models.CharField(blank=True, max_length=10, verbose_name='PUK do Cartão'),
        ),
    ]
