# Generated by Django 5.2.4 on 2025-07-11 12:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0003_nome_so_alter_nome_equipamento_1_nome_equipamento'),
        ('informatica', '0003_alter_cartaotelemovel_numero_cartao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventarioequipamento',
            name='tamanho',
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='sistema_operacional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.nome_so', verbose_name='Sistema Operacional'),
        ),
    ]
