# Generated by Django 5.2.4 on 2025-07-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0004_remove_inventarioequipamento_tamanho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='mac',
            field=models.CharField(blank=True, max_length=30, verbose_name='Mac Address'),
        ),
    ]
