# Generated by Django 5.2.4 on 2025-07-11 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0003_nome_so_alter_nome_equipamento_1_nome_equipamento'),
        ('informatica', '0005_alter_inventarioequipamento_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventarioequipamento',
            name='atribuido_check',
            field=models.BooleanField(default=False, verbose_name='Atribuído?'),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='atribuido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comum.utilizador', verbose_name='Utilizador'),
        ),
    ]
