# Generated by Django 5.2.4 on 2025-07-24 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0006_inventarioequipamento_atribuido_check_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='nome_rede',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nome na Rede'),
        ),
    ]
