# Generated by Django 5.2.4 on 2025-07-24 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0007_alter_inventarioequipamento_nome_rede'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='nome_rede',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Nome na Rede'),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Número de Série'),
        ),
    ]
