# Generated by Django 5.2.4 on 2025-07-25 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0008_alter_inventarioequipamento_nome_rede_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventario',
            options={'verbose_name_plural': 'Inventários'},
        ),
        migrations.AlterModelOptions(
            name='inventarioequipamento',
            options={'verbose_name_plural': 'Inventário Equipamentos TrueClinic'},
        ),
        migrations.RemoveField(
            model_name='aparelhotelemovel',
            name='telemovel',
        ),
        migrations.AddField(
            model_name='aparelhotelemovel',
            name='estatus_telemovel',
            field=models.CharField(choices=[('alocado', 'Alocado'), ('estoque', 'Estoque'), ('descartado', 'Descartado')], default='em_uso', max_length=10, verbose_name='Estatus'),
        ),
        migrations.AlterField(
            model_name='aparelhotelemovel',
            name='cartao',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='informatica.cartaotelemovel'),
        ),
        migrations.AlterField(
            model_name='aparelhotelemovel',
            name='nome_utilizador',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='informatica.inventario'),
        ),
    ]
