# Generated by Django 5.2.4 on 2025-07-25 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0009_alter_inventario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparelhotelemovel',
            name='cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='informatica.cartaotelemovel'),
        ),
        migrations.AlterField(
            model_name='aparelhotelemovel',
            name='nome_utilizador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='informatica.inventario'),
        ),
        migrations.AlterField(
            model_name='aparelhotelemovel',
            name='numero_telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Numero do Telemóvel'),
        ),
    ]
