# Generated by Django 5.2.4 on 2025-07-25 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comum', '0007_alter_emailstrue_email'),
        ('informatica', '0010_alter_aparelhotelemovel_cartao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aparelhotelemovel',
            name='nome_utilizador',
        ),
        migrations.AddField(
            model_name='aparelhotelemovel',
            name='atribuido_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comum.utilizador'),
        ),
        migrations.AddField(
            model_name='aparelhotelemovel',
            name='inventario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='aparelhos', to='informatica.inventario', verbose_name='Inventário'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aparelhotelemovel',
            name='cartao',
            field=models.ForeignKey(blank=True, default=4, on_delete=django.db.models.deletion.PROTECT, to='informatica.cartaotelemovel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aparelhotelemovel',
            name='editado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='aparelhotelemovel',
            name='estatus_telemovel',
            field=models.CharField(choices=[('alocado', 'Alocado'), ('estoque', 'Estoque'), ('descartado', 'Descartado')], default='alocado', max_length=10),
        ),
        migrations.AlterField(
            model_name='aparelhotelemovel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='aparelhotelemovel',
            name='marca_esquipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.marca'),
        ),
        migrations.AlterField(
            model_name='aparelhotelemovel',
            name='modelo_esquipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.modelo'),
        ),
        migrations.AlterField(
            model_name='aparelhotelemovel',
            name='numero_telefone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='aparelhotelemovel',
            name='registado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cartaotelemovel',
            name='atribuido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.utilizador'),
        ),
        migrations.AlterField(
            model_name='cartaotelemovel',
            name='editado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='cartaotelemovel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cartaotelemovel',
            name='numero_cartao',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='cartaotelemovel',
            name='numero_telefone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cartaotelemovel',
            name='pin',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='cartaotelemovel',
            name='plano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.planostelemoveis'),
        ),
        migrations.AlterField(
            model_name='cartaotelemovel',
            name='puk',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='cartaotelemovel',
            name='registado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emailcompartilhado',
            name='editado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emailcompartilhado',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='emailcompartilhado',
            name='registado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='equipamentos',
            name='editado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='equipamentos',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipamentos',
            name='nome_equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='informatica.inventarioequipamento'),
        ),
        migrations.AlterField(
            model_name='equipamentos',
            name='registado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='editado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='registado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='atribuido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='comum.utilizador'),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='atribuido_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='data_compra',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='data_garantia',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='descricao_equipamento',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='editado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='estatus_equipamento',
            field=models.CharField(choices=[('em_uso', 'Em Uso'), ('desuso', 'Desuso'), ('descartado', 'Descartado')], default='em_uso', max_length=10),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='fatura',
            field=models.FileField(blank=True, upload_to='%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.fornecedor'),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='mac',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='marca_esquipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.marca'),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='memoria',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='modelo_esquipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.modelo'),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='nome_equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.nome_equipamento_1'),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='nome_rede',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='numero_ip',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='registado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='sistema_operacional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.nome_so'),
        ),
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='tipo_garantia',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.DeleteModel(
            name='CraicaoUtilizador',
        ),
    ]
