# Generated by Django 5.2.4 on 2025-07-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0011_remove_aparelhotelemovel_nome_utilizador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aparelhotelemovel',
            name='inventario',
        ),
    ]
