# Generated by Django 5.2.4 on 2025-07-25 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0012_remove_aparelhotelemovel_inventario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparelhotelemovel',
            name='cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='informatica.cartaotelemovel'),
        ),
    ]
