# Generated by Django 5.2.4 on 2025-07-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0013_alter_aparelhotelemovel_cartao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='fatura',
            field=models.FileField(blank=True, upload_to='faturas/'),
        ),
    ]
