# Generated by Django 5.2.4 on 2025-07-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0014_alter_inventarioequipamento_fatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='atribuido_check',
            field=models.BooleanField(default=False, verbose_name='Atribuido'),
        ),
    ]
