# Generated by Django 5.2.4 on 2025-07-28 14:45

import cloudinary_storage.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatica', '0015_alter_inventarioequipamento_atribuido_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventarioequipamento',
            name='fatura',
            field=models.FileField(blank=True, storage=cloudinary_storage.storage.MediaCloudinaryStorage(), upload_to='faturas/'),
        ),
    ]
