# Generated by Django 5.2.4 on 2025-07-10 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomeSinistrado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registado', models.DateTimeField(auto_now_add=True, verbose_name='Registado em:')),
                ('editado', models.DateTimeField(auto_now_add=True, verbose_name='Alterado em: ')),
                ('nome_sinistrado', models.CharField(max_length=500, verbose_name='Nome do Sinistrado')),
                ('numero_nif', models.CharField(max_length=50, unique=True, verbose_name='Número do NIF')),
                ('link_imagem', models.CharField(blank=True, max_length=300, verbose_name='Link das Imagens')),
            ],
            options={
                'verbose_name_plural': 'Imagens dos Exames',
            },
        ),
        migrations.CreateModel(
            name='RegistoExames',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('registado', models.DateTimeField(auto_now_add=True, verbose_name='Registado em:')),
                ('data_exame', models.DateField(verbose_name='Data do Exame')),
                ('caixa', models.IntegerField(verbose_name='Caixa do Exame')),
                ('nome_exame', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='comum.nomeexame', verbose_name='Nome do Exame')),
                ('nome_sinistrado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consulta.nomesinistrado')),
            ],
            options={
                'verbose_name_plural': 'Registos dos Exames',
            },
        ),
    ]
