# Generated by Django 5.2.4 on 2025-07-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consulta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomesinistrado',
            name='numero_nif',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Número do NIF'),
        ),
    ]
