# Generated by Django 5.2.4 on 2025-08-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_ticketattachment_ticketcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reporter_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='reporter_nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
